name       : perl-gtk3-imageview
version    : 6
release    : 1
source     :
    - https://cpan.metacpan.org/authors/id/R/RA/RATCLIFFE/Gtk3-ImageView-6.tar.gz : c01d623e7a6053a61024aed320da20ab3a40f464b7003e75932fc311938b334f
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Gtk3::ImageView - Image viewer widget for Gtk3
description: |
    The Gtk3::ImageView widget allows the user to zoom, pan and select the specified image and provides hooks to allow additional tools, e.g. painter, to be created and used.
builddeps  :
    - perl
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
